### ISSUE TITLE
Cannot load shapes due to 'column does not exist' error

### ISSUE THREAD

**Issue by Mijutra** [MARS-Group-HAW/esida-db#1]
**OS:** Linux 22.04.3 LTS Jammy

**Description:** \
When executing `sudo docker-compose exec esida python ./esida-cli.py load-shapes ./input/shapes/esida_tza.gpkg` I get the error `psycopg2.errors.UndefinedColumn: column "parent_id" of relation "shape" does not exist`. \
I executed ` sudo docker-compose exec esida flask create-db` like mentioned in the `README.md` file.

```
user@user-device-name:~/Git/esida-db$ sudo docker-compose exec esida flask create-db
[sudo] password for user: 
user@user-device-name:~/Git/esida-db$ sudo docker-compose exec esida python ./esida-cli.py load-shapes ./input/shapes/esida_tza.gpkg
Traceback (most recent call last):
  File "/app/./esida-cli.py", line 471, in <module>
    cli()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/app/./esida-cli.py", line 62, in load_shapes
    gdf_with_parent[required_cols].to_postgis('shape', connect(), if_exists='append')
  File "/usr/local/lib/python3.10/dist-packages/geopandas/geodataframe.py", line 1931, in to_postgis
    geopandas.io.sql._write_postgis(
  File "/usr/local/lib/python3.10/dist-packages/geopandas/io/sql.py", line 445, in _write_postgis
    gdf.to_sql(
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py", line 2987, in to_sql
    return sql.to_sql(
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/sql.py", line 695, in to_sql
    return pandas_sql.to_sql(
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/sql.py", line 1738, in to_sql
    total_inserted = sql_engine.insert_records(
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/sql.py", line 1325, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/sql.py", line 946, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "/usr/local/lib/python3.10/dist-packages/geopandas/io/sql.py", line 334, in _psql_insert_copy
    cur.copy_expert(sql=sql, file=s_buf)
psycopg2.errors.UndefinedColumn: column "parent_id" of relation "shape" does not exist
```

**Comment by stroebjo** [comment]
I suppose, you created the database scheme before the PostGIS-Setup was finished. 

Please try the following:

- restart the PostGIS container
- drop the database: `$ docker-compose exec esida flask drop-db`
- recreate the scheme: `$ docker-compose exec esida flask create-db`
- now the import of the shapes should work: `$ docker-compose exec esida python ./esida-cli.py load-shapes ./input/shapes/esida_tza.gpkg`

**Comment by Mijutra** [comment]
This worked like a charm!
Thanks.
